
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/iHZW/WFPodSpecs.git'
#source 'https://github.com/iHZW/WFLibSpec.git'

#flutter_application_path = "../Flutter/flutter_module"
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

####  Debug调试相关 ####
def debugTool
  # debug工具

  # 查看UI结构
  pod 'LookinServer', '1.0.4', :configurations => ['Debug','QA','QA_Dev']

  # DoKit
  pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug','QA','QA_Dev']
#  pod 'DoraemonKit/WithLogger', '~> 3.0.4', :configurations => ['Debug','QA','QA_Dev']
#  pod 'DoraemonKit/WithGPS', '~> 3.0.4', :configurations => ['Debug','QA','QA_Dev']
#  pod 'DoraemonKit/WithLoad', '~> 3.0.4', :configurations => ['Debug','QA','QA_Dev']
#  pod 'DoraemonKit/WithMLeaksFinder', '~> 3.0.4', :configurations => ['Debug','QA','QA_Dev']

  pod 'DoraemonKit/WithLogger', :configurations => ['Debug','QA','QA_Dev']
  pod 'DoraemonKit/WithGPS', :configurations => ['Debug','QA','QA_Dev']
  pod 'DoraemonKit/WithLoad',:configurations => ['Debug','QA','QA_Dev']
#  pod 'DoraemonKit/WithMLeaksFinder', :configurations => ['Debug','QA','QA_Dev']
end


target 'My_Study' do

  use_frameworks!
  
  #常用引入pod方式
  #0、指定版本号
  #pod 'xxxx', '~> 1.1.2'     //使用大于等于1.1.2但小于1.2的版本
  #pod 'xxxx', '> 1.1.2'        //使用高于1.1.2的版本
  #pod 'xxxx', '1.1.2'          //只使用1.1.2版本
  
  #1、指定导入库的podspec文件路径
  #pod 'xxxx', :podspec => 'podspec文件路径'
  
  #2、指定导入库的源码git地址
  #pod 'xxxx', :git => '源码git地址'
  
  #3、指定导入库的Tag分支
  #pod 'xxxx', :tag => 'tag名'
  
  #4、指定本地的某个库,文件夹中要有podspec文件
  #pod 'xxxx', :path => '~/Documents/AFNetworking'

  
  # 返回侧滑适配有导航栏和没导航栏的切换
  pod 'FDFullscreenPopGesture', '~> 1.1'

  pod 'AFNetworking', '~> 4.0.1'
  pod 'Masonry','1.1.0'
  pod 'JSONModel','1.5.0'
  pod 'MJExtension','3.0.15.1'
  pod 'MJRefresh','3.1.15.7'
  pod 'PINCache','2.3'
  pod 'SDWebImage', '5.13.2'
#  将抽屉控件放到工程里, 稍微做下调整
#  pod 'CWLateralSlide', '1.6.5'
  pod 'PINCache','2.3'
  pod 'KissXML','5.2.3'
  pod 'FMDB','>=2.7.1'
#  钥匙串 和永久保存使用
  pod 'SAMKeychain', '1.5.3'
#   播放器
  pod 'SJVideoPlayer', '3.4.3'
  
  pod 'CocoaAsyncSocket'
  
  #本地库
#  pod 'MJUtils', :path => 'LocalLib/MJUtils'
#  pod 'WFUtilsLib'
#  pod 'MJMonkeyLib'
#  pod 'WFEOCFamilyLib'
#  pod 'WFUIKit'
  
  pod 'YYKit', '1.0.9'
  
#  pod 'YYCategories'
#  加载SVG图片资源使用
  pod 'SVGKit', '2.1.1'
  
  pod 'KVOController', '1.2.0'
  
  pod 'ReactiveObjC', '3.1.1'
  
  pod 'YTKNetwork', '3.0.6'
  
  #install_all_flutter_pods(flutter_application_path)
 
  pod 'Alamofire', '4.9.1'

  # Debug调试工具
  debugTool
 
  # 高德地图
  pod 'AMapLocation-NO-IDFA'
  pod 'AMap3DMap-NO-IDFA'
  pod 'AMapSearch-NO-IDFA'
  pod 'SSZipArchive', '2.4.3'
 
  # VLC 是一款强大的全平台播放器
  #pod 'MobileVLCKit' #下载不下来，网络不行
 
  # pod 'MBProgressHUD', '1.2.0'

  # logan  美团日志
  pod 'Logan', '1.2.7'
  
  # 骨架屏
  pod 'TABAnimated', '2.6.3'

  # 富文本
#  pod 'ChainAttributedString'

  #  pod 'Aspects', '1.4.1'
  pod 'HookLib', :path => './LocalPodsLib/BasicLib/HookLib/'

  # 微信SDK
  pod 'WechatOpenSDK', '1.9.7'
  
  #腾讯QMUI框架
  pod 'QMUIKit', '4.1.3'
  
  # 组件化路由
  pod 'MGJRouter', :git => 'https://github.com/lyujunwei/MGJRouter'
  
  # 保护App不闪退
  pod 'JJException', '0.2.12'
  
  # 主流转场动画
  pod 'HHTransition', '3.1.0'
  
  # 网络层封装（配合VM）
  pod 'YTKNetwork', '3.0.6'
  
  # 组件化路由库
  pod 'JLRoutes', '2.1'
  
  #全屏返回
  pod 'FDFullscreenPopGesture', '1.1'
  # 滚动视图返回
  pod 'TZScrollViewPopGesture', '1.0.6'
  
  #闪验
  pod 'CL_ShanYanSDK', '2.3.5.8'
  
  #键盘
  pod 'IQKeyboardManager', '6.5.10'
  # 个推
  pod 'GTSDK', '2.7.1.0'
  # TabBar
  pod 'CYLTabBarController', '1.29.2'
  
  # crash拦截
  pod 'JJException', '0.2.12'
  # Bugly
  pod 'Bugly', '~> 2.5.9'

  pod 'BRPickerView', '2.8.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  
#  处理 layoutCache[currentClass] = ivars报错
#  find_and_replace("Pods/FBRetainCycleDetector/FBRetainCycleDetector/Layout/Classes/FBClassStrongLayout.mm",
#    "layoutCache[currentClass] = ivars;", "layoutCache[(id<NSCopying>)currentClass] = ivars;")

  # 解决pod库带bundle资源时 需要手动选择team的问题
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["DEVELOPMENT_TEAM"] = "82MDUB8B2X"  #teamid
      end
    end
  end
end



target 'My_StudyNotificationService' do
  platform :ios, "10.0"
  
  use_frameworks! :linkage =>:static
  pod 'GTExtensionSDK', '3.0.1'
  
end




