
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/iHZW/WFPodSpecs.git'
#source 'https://github.com/iHZW/WFLibSpec.git'

#flutter_application_path = "../Flutter/flutter_module"
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

####  Debug调试相关 ####
def debugTool
  # debug工具

  # 查看UI结构
  pod 'LookinServer', '1.0.4',  :configurations => ['Debug','QA','QA_Dev']

  # DoKit
  pod 'DoraemonKit/Core', '3.1.3',  :configurations => ['Debug','QA','QA_Dev']
#  pod 'DoraemonKit/Core', '3.1.3', :configurations => ['Debug','QA','QA_Dev']

end


target 'My_Study' do

  use_frameworks!
  
  # 返回侧滑适配有导航栏和没导航栏的切换
  pod 'FDFullscreenPopGesture', '~> 1.1'

  pod 'AFNetworking', '~> 4.0.1'
  pod 'Masonry','1.1.0'
  pod 'JSONModel','1.5.0'
  pod 'MJExtension','3.0.15.1'
  pod 'MJRefresh','3.1.15.7'
  pod 'PINCache','2.3'
  pod 'SDWebImage', '5.13.2'
#  将抽屉控件放到工程里, 稍微做下调整
#  pod 'CWLateralSlide', '1.6.5'
  pod 'PINCache','2.3'
  pod 'KissXML','5.2.3'
  pod 'FMDB','>=2.7.1'
#  钥匙串 和永久保存使用
  pod 'SAMKeychain', '1.5.3'
#   播放器
  pod 'SJBaseVideoPlayer', '3.5.2'
  
  pod 'CocoaAsyncSocket'
  
  #本地库
#  pod 'MJUtils', :path => 'LocalLib/MJUtils'
#  pod 'WFUtilsLib'
#  pod 'MJMonkeyLib'
#  pod 'WFEOCFamilyLib'
#  pod 'WFUIKit'
  
  pod 'YYKit', '1.0.9'
#  加载SVG图片资源使用
  pod 'SVGKit', '2.1.1'
  
  pod 'KVOController', '1.2.0'
  
  pod 'ReactiveObjC', '3.1.1'
  
  #install_all_flutter_pods(flutter_application_path)
 
  pod 'Alamofire', '4.9.1'

  # Debug调试工具
  debugTool
 
  # 高德地图
  pod 'AMapLocation-NO-IDFA'
  pod 'AMap3DMap-NO-IDFA'
  pod 'AMapSearch-NO-IDFA'
  pod 'SSZipArchive', '2.4.3'
 
  # VLC 是一款强大的全平台播放器
  #pod 'MobileVLCKit' #下载不下来，网络不行
 
  # pod 'MBProgressHUD', '1.2.0'

  # logan  美团日志
  pod 'Logan', '1.2.7'
  
  # 骨架屏
  pod 'TABAnimated', '2.6.3'

  # 富文本
#  pod 'ChainAttributedString'

#  pod 'Aspects', '1.4.1'
pod 'HookLib', :path => './LocalPodsLib/BasicLib/HookLib/'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end



